compute min/max

In [5]:
import numpy as np
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a


array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [6]:
a.max()

9

How to get the items present in series A and not in series B

In [9]:
import pandas as pd
p1 = pd.Series([2, 4, 6, 8, 10])
p2 = pd.Series([8, 10, 12, 14, 16])
print(p1)
print()
print(p2)

0     2
1     4
2     6
3     8
4    10
dtype: int64

0     8
1    10
2    12
3    14
4    16
dtype: int64


In [11]:
p1[~p1.isin(p2)]

0    2
1    4
2    6
dtype: int64

explain what is vectorisation in Numpy with a code example

In [13]:
a_array = np.array([1,2,3])
b_array = np.array([4,5,6])
print(a_array,b_array,sep="\n")

[1 2 3]
[4 5 6]


In [19]:
def add_square(a,b):
    return(a+b)**2
vadd_square = np.vectorize(add_square)
vadd_square(a_array,b_array)

array([25, 49, 81])

How to get the items not common to both series A and series B

In [21]:

p1 = pd.Series([2, 4, 6, 8, 10])
p2 = pd.Series([8, 10, 12, 14, 16])
print(p1)
print()
print(p2)

0     2
1     4
2     6
3     8
4    10
dtype: int64

0     8
1    10
2    12
3    14
4    16
dtype: int64


In [27]:
p1[~p1.isin(p2)]
p_u = pd.Series(np.union(p1,p2))
p_i = pd.Series(np.inter(p1,p2))
p_u[~p_i.isin(p_u)]

AttributeError: module 'numpy' has no attribute 'union'

Find the mean of the array

In [34]:
arr = np.array([[20, 15, 37], [47, 13,np.nan]])

In [36]:
np.nanmean(arr)S

SyntaxError: invalid syntax (1211712188.py, line 1)

How can you find the row for which the value of a specific column is max and min


In [38]:
data = {
  "sales": [23, 34, 56],
  "age": [50, 40, 30]
}
df = pd.DataFrame(data)
df

sales  age
0     23   50
1     34   40
2     56   30

In [41]:
df[df.sales==df.sales.max()]

sales  age
2     56   30

In [48]:
df[df.sales==df.sales.min()]

sales  age
0     23   50

In [47]:
print(df.idxmax())
print(df.idxmin())

sales    2
age      0
dtype: int64
sales    0
age      2
dtype: int64


given a two numpy arrays, the task is to multiply 2d numpy array with 1d numpy array each row corresponding to one element in numpy

In [50]:
ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
ini_array2 = np.array([0, 2, 3])
print(ini_array1,ini_array2,sep="\n\n")

[[1 2 3]
 [2 4 5]
 [1 2 3]]

[0 2 3]


In [53]:
ini_array3 = ini_array1*ini_array2
print(ini_array3)

[[ 0  4  9]
 [ 0  8 15]
 [ 0  4  9]]


In [57]:
ini_array3 = ini_array1*ini_array2[:,np.newaxis]
print(ini_array3)

[[ 0  0  0]
 [ 4  8 10]
 [ 3  6  9]]


In [58]:
ini_array3 = ini_array1*ini_array2[:,None]
print(ini_array3)

[[ 0  0  0]
 [ 4  8 10]
 [ 3  6  9]]


In [59]:
ini_array3 = (ini_array1*ini_array2).T
print(ini_array3)

[[ 0  0  0]
 [ 4  8  4]
 [ 9 15  9]]
